.TH DVTM 1 dvtm\-VERSION
.SH NAME
dvtm \- dynamic virtual terminal manager
.SH SYNOPSIS
.B dvtm
.RB [ \-v ] \ [ \-m \ mod ] \ [ \-s \ status-fifo ] \ [cmd...]
.SH DESCRIPTION
dvtm is a dynamic tiling window manager for the console.
As a console window manager it tries to make it easy to work with multiple
console based applications.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.TP
.B \-m mod
set default modifier at runtime.
.TP
.B \-d escdelay
set the delay ncurses waits before deciding if a character that might be part
of an escape sequence is actually part of an escape sequence.
.TP
.B \-h nnn
set the scrollback history buffer size at runtime.
.TP
.B \-s status-fifo
if status-fifo is a named pipe it's content is read and displayed. See the dvtm-status script
for an usage example.
.TP
.B [cmd...]
Execute cmd after dvtm is started.
.SH USAGE
.SS Keyboard commands
.TP
.B Mod
Each keybinding begins with Mod which defaults to ^g but can be changed in config.h or with
the -m command line option.
.TP
.B Mod\-c
Create a new shell window.
.TP
.B Mod\-x
Close focused window.
.TP
.B Mod\-l
Increases the master area width about 5% (all except grid and fullscreen layout).
.TP
.B Mod\-h
Decreases the master area width about 5% (all except grid and fullscreen layout).
.TP
.B Mod\-j
Focus next window.
.TP
.B Mod\-k
Focus previous window.
.TP
.B Mod\-[1..n]
Focus the
.BR nth
window.
.TP
.B Mod\-.
Toggle minimization of current window.
.TP
.B Mod\-u
Focus next non minimized window.
.TP
.B Mod\-i
Focus prev non minimized window.
.TP
.B Mod\-m
Maximize current window (change to fullscreen layout).
.TP
.B Mod\-PageUp
Scroll up.
.TP
.B Mod\-PageDown
Scroll down.
.TP
.B Mod\-Space
Toggle between defined layouts (affects all windows).
.TP
.B Mod\-Enter
Zooms/cycles current window to/from master area.
.TP
.B Mod\-t
Change to vertical stack tiling layout.
.TP
.B Mod\-b
Change to bottom stack tiling layout.
.TP
.B Mod\-g
Change to grid layout.
.TP
.B Mod\-s
Shows/hides the status bar.
.TP
.B Mod\-L
Redraw whole screen.
.TP
.B Mod\-G
Escape the next typed key.
.TP
.B Mod\-X
Lock screen.
.TP
.B Mod\-M
Toggle dvtm mouse grabbing.
.B Mod\-q
Quit dvtm.
.SS Mouse commands
.TP
.B Copy and Paste
By default dvtm captures mouse events to provide the actions listed below. Unfortunately
this interferes with the standard X copy and paste mechanism. To work around this
you need to hold down SHIFT while selecting or pasting text. Alternatively you can
disable mouse support at compile time, or use Mod\-M to toggle mouse support dynamically.
.TP
.B Button1 click
Select window.
.TP
.B Button1 double click
Select window and toggle maximization.
.TP
.B Button2 click
Zooms/cycles current window to/from master area.
.TP
.B Button3 click
Toggle minimization of current window.

.SH EXAMPLE
.TP
See the dvtm-status script as an example.

.SH CUSTOMIZATION
dvtm is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.

.SH AUTHOR
dvtm is written by Marc Andre Tanner <mat at brain-dump.org>
